SECRET_KEY = '$@*rxtcyvubnjmkOIUYT$$#@'
DEBUG = True # APENAS SE VC QUISER ESSA FUNÇÃO, SE NÃO; "False"
HOST = '127.0.0.1' # APENAS SE ESTIVER USANDO LOCAL, SE NÃO; COMENTA ESSA LINHA
PORT = 5000

MONGODB_DB = ''
MONGODB_HOST = ''
MONGODB_PORT = 53295
MONGODB_USERNAME = ''
MONGODB_PASSWORD = ""

# mongodb://<dbuser>:<dbpassword>@ds053295.mlab.com:53295/grp_prazo
